// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmlnbRa9S-wJgnTT_7qQ5PzkRxHJPZzLk',
    appId: '1:500660266579:web:e6027d8711f78c0f0148a6',
    messagingSenderId: '500660266579',
    projectId: 'todo-dcd47',
    authDomain: 'todo-dcd47.firebaseapp.com',
    storageBucket: 'todo-dcd47.firebasestorage.app',
    measurementId: 'G-LCN28E1EP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB73CacTiHCPWcQC7xo3jIblt9bwa7fN9o',
    appId: '1:500660266579:android:843c0151867491c00148a6',
    messagingSenderId: '500660266579',
    projectId: 'todo-dcd47',
    storageBucket: 'todo-dcd47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXutwrSDilQtaalqnSkTgOm9cNT3E_o40',
    appId: '1:500660266579:ios:ee9e5e87b340b8eb0148a6',
    messagingSenderId: '500660266579',
    projectId: 'todo-dcd47',
    storageBucket: 'todo-dcd47.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXutwrSDilQtaalqnSkTgOm9cNT3E_o40',
    appId: '1:500660266579:ios:ee9e5e87b340b8eb0148a6',
    messagingSenderId: '500660266579',
    projectId: 'todo-dcd47',
    storageBucket: 'todo-dcd47.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmlnbRa9S-wJgnTT_7qQ5PzkRxHJPZzLk',
    appId: '1:500660266579:web:ee838eb0e66b26740148a6',
    messagingSenderId: '500660266579',
    projectId: 'todo-dcd47',
    authDomain: 'todo-dcd47.firebaseapp.com',
    storageBucket: 'todo-dcd47.firebasestorage.app',
    measurementId: 'G-P2E11K8H86',
  );
}
